"""儲存層（ADR-0005）：文件式 SQLite＋內容雜湊 blob＋append-only repositories。"""

from visionforge_core.storage.database import MAX_SCHEMA, Database
from visionforge_core.storage.errors import (
    ConflictError,
    NotAProjectError,
    NotFoundError,
    ProjectSchemaTooNewError,
    StorageError,
)
from visionforge_core.storage.media_store import MediaBlobStore
from visionforge_core.storage.project import Project, create_project, open_project
from visionforge_core.storage.repositories import (
    AnnotationRepository,
    CapabilityReleaseRepository,
    ClaimTeachingContextRepository,
    ConceptRepository,
    CostRepository,
    CoverageRepository,
    DatasetVersionRepository,
    DecisionRepository,
    EvaluationFeedbackRepository,
    EvaluationRepository,
    GoldenRepository,
    LabelRepository,
    ManifestRepository,
    MediaAssignmentRepository,
    MediaRepository,
    ModelArtifactRepository,
    ReviewEventRepository,
    RunRepository,
    TaskRepository,
    TeacherConsentRepository,
    TrainingRunRepository,
)

__all__ = [
    "MAX_SCHEMA",
    "AnnotationRepository",
    "CapabilityReleaseRepository",
    "ClaimTeachingContextRepository",
    "ConceptRepository",
    "ConflictError",
    "CostRepository",
    "CoverageRepository",
    "DatasetVersionRepository",
    "Database",
    "DecisionRepository",
    "EvaluationRepository",
    "EvaluationFeedbackRepository",
    "GoldenRepository",
    "LabelRepository",
    "ManifestRepository",
    "MediaAssignmentRepository",
    "MediaBlobStore",
    "MediaRepository",
    "ModelArtifactRepository",
    "NotAProjectError",
    "NotFoundError",
    "Project",
    "ProjectSchemaTooNewError",
    "ReviewEventRepository",
    "RunRepository",
    "TaskRepository",
    "TeacherConsentRepository",
    "TrainingRunRepository",
    "StorageError",
    "create_project",
    "open_project",
]
