"""契約模組：核心與一切 Provider 的唯一耦合點（憲法 PR2）。"""

from visionforge_core.contracts.claims import (
    SCHEMA_VERSION,
    Assertion,
    BBox,
    Claim,
    Concept,
    ConceptMappingProvenance,
    Confidence,
    InferenceRun,
    Keypoints,
    Label,
    MaskRef,
    MediaSubject,
    Point,
    Polygon,
    Producer,
    Reliability,
    Review,
    ReviewStatus,
    UnknownGeometry,
    WholeImage,
)

__all__ = [
    "SCHEMA_VERSION",
    "Assertion",
    "BBox",
    "Claim",
    "Concept",
    "ConceptMappingProvenance",
    "Confidence",
    "InferenceRun",
    "Keypoints",
    "Label",
    "MaskRef",
    "MediaSubject",
    "Point",
    "Polygon",
    "Producer",
    "Reliability",
    "Review",
    "ReviewStatus",
    "UnknownGeometry",
    "WholeImage",
]
